/* Generated by re2rust */


#![allow(clippy::all)]
use super::token::{Token, TokenKind};
use super::lexer_error::{LexerError, LexerErrorKind};
use super::lexer::Lexer;

#[allow(unused_braces)]
#[rustfmt::skip]
impl<'src> Lexer<'src> {
    pub fn next(&mut self) -> Result<Token<'src>, LexerError<'src>>  {
        self.next_internal(true)
    }

    pub(crate) fn next_internal(&mut self, use_peek_queue: bool) -> Result<Token<'src>, LexerError<'src>> {
        if use_peek_queue {
            if let Some(next) = self.peek_queue.pop_front() {
                return next;
            }
        }
        if let Some(forced) = self.force_next_token.take() {
            return Ok(forced);
        }

        if self.eof { return self.error(LexerErrorKind::EofReached); }

        self.token = self.cursor;

        
{
    #[allow(unused_assignments)]
    let mut yych : u8 = 0;
    let mut yyaccept : usize = 0;
    let mut yystate : usize = self.cond;
    'yyl: loop {
        match yystate {
            0 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x09 ..= 0x0C |
                    0x20 => {
                        self.cursor += 1;
                        yystate = 2;
                        continue 'yyl;
                    }
                    0x21 => {
                        self.cursor += 1;
                        yystate = 4;
                        continue 'yyl;
                    }
                    0x22 => {
                        self.cursor += 1;
                        yystate = 6;
                        continue 'yyl;
                    }
                    0x25 => {
                        self.cursor += 1;
                        yystate = 7;
                        continue 'yyl;
                    }
                    0x28 => {
                        self.cursor += 1;
                        yystate = 8;
                        continue 'yyl;
                    }
                    0x29 => {
                        self.cursor += 1;
                        yystate = 9;
                        continue 'yyl;
                    }
                    0x2A => {
                        self.cursor += 1;
                        yystate = 10;
                        continue 'yyl;
                    }
                    0x2B => {
                        self.cursor += 1;
                        yystate = 12;
                        continue 'yyl;
                    }
                    0x2C => {
                        self.cursor += 1;
                        yystate = 14;
                        continue 'yyl;
                    }
                    0x2D => {
                        self.cursor += 1;
                        yystate = 15;
                        continue 'yyl;
                    }
                    0x2E => {
                        self.cursor += 1;
                        yystate = 17;
                        continue 'yyl;
                    }
                    0x2F => {
                        self.cursor += 1;
                        yystate = 18;
                        continue 'yyl;
                    }
                    0x30 ..= 0x39 => {
                        self.cursor += 1;
                        yystate = 20;
                        continue 'yyl;
                    }
                    0x3A => {
                        self.cursor += 1;
                        yystate = 22;
                        continue 'yyl;
                    }
                    0x3B => {
                        self.cursor += 1;
                        yystate = 23;
                        continue 'yyl;
                    }
                    0x3C => {
                        self.cursor += 1;
                        yystate = 24;
                        continue 'yyl;
                    }
                    0x3D => {
                        self.cursor += 1;
                        yystate = 26;
                        continue 'yyl;
                    }
                    0x3E => {
                        self.cursor += 1;
                        yystate = 28;
                        continue 'yyl;
                    }
                    0x41 ..= 0x5A |
                    0x64 |
                    0x67 ..= 0x68 |
                    0x6A ..= 0x6B |
                    0x71 |
                    0x76 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    0x5B => {
                        self.cursor += 1;
                        yystate = 33;
                        continue 'yyl;
                    }
                    0x5D => {
                        self.cursor += 1;
                        yystate = 34;
                        continue 'yyl;
                    }
                    0x5F => {
                        self.cursor += 1;
                        yystate = 35;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 37;
                        continue 'yyl;
                    }
                    0x62 => {
                        self.cursor += 1;
                        yystate = 38;
                        continue 'yyl;
                    }
                    0x63 => {
                        self.cursor += 1;
                        yystate = 39;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 40;
                        continue 'yyl;
                    }
                    0x66 => {
                        self.cursor += 1;
                        yystate = 41;
                        continue 'yyl;
                    }
                    0x69 => {
                        self.cursor += 1;
                        yystate = 42;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 43;
                        continue 'yyl;
                    }
                    0x6D => {
                        self.cursor += 1;
                        yystate = 44;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 45;
                        continue 'yyl;
                    }
                    0x6F => {
                        self.cursor += 1;
                        yystate = 46;
                        continue 'yyl;
                    }
                    0x70 => {
                        self.cursor += 1;
                        yystate = 47;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 48;
                        continue 'yyl;
                    }
                    0x73 => {
                        self.cursor += 1;
                        yystate = 49;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 50;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 51;
                        continue 'yyl;
                    }
                    0x7B => {
                        self.cursor += 1;
                        yystate = 52;
                        continue 'yyl;
                    }
                    0x7D => {
                        self.cursor += 1;
                        yystate = 53;
                        continue 'yyl;
                    }
                    _ => {
                        if self.input.len() - self.cursor < 1 {
                            yystate = 184;
                            continue 'yyl;
                        }
                        self.cursor += 1;
                        yystate = 1;
                        continue 'yyl;
                    }
                }
            }
            1 => { return self.error(LexerErrorKind::UnexpectedCharacter(self.token_text())) },
            2 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x09 ..= 0x0C |
                    0x20 => {
                        self.cursor += 1;
                        yystate = 2;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 3;
                        continue 'yyl;
                    }
                }
            }
            3 => { return self.token(TokenKind::Whitespace(self.token_text())) },
            4 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x3D => {
                        self.cursor += 1;
                        yystate = 54;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 5;
                        continue 'yyl;
                    }
                }
            }
            5 => { return self.token(TokenKind::Bang) },
            6 => {
                self.cond = YYC_STRING;
                { return self.token(TokenKind::StringInterpolationStart); }
            }
            7 => { return self.token(TokenKind::Percent) },
            8 => { return self.token(TokenKind::LParen) },
            9 => { return self.token(TokenKind::RParen) },
            10 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x2A => {
                        self.cursor += 1;
                        yystate = 55;
                        continue 'yyl;
                    }
                    0x3D => {
                        self.cursor += 1;
                        yystate = 56;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 11;
                        continue 'yyl;
                    }
                }
            }
            11 => { return self.token(TokenKind::Star) },
            12 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 => {
                        self.cursor += 1;
                        yystate = 20;
                        continue 'yyl;
                    }
                    0x3D => {
                        self.cursor += 1;
                        yystate = 57;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 13;
                        continue 'yyl;
                    }
                }
            }
            13 => { return self.token(TokenKind::Plus) },
            14 => { return self.token(TokenKind::Comma) },
            15 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 => {
                        self.cursor += 1;
                        yystate = 20;
                        continue 'yyl;
                    }
                    0x3D => {
                        self.cursor += 1;
                        yystate = 58;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 16;
                        continue 'yyl;
                    }
                }
            }
            16 => { return self.token(TokenKind::Minus) },
            17 => { return self.token(TokenKind::Dot) },
            18 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x2F => {
                        self.cursor += 1;
                        yystate = 59;
                        continue 'yyl;
                    }
                    0x3D => {
                        self.cursor += 1;
                        yystate = 61;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 19;
                        continue 'yyl;
                    }
                }
            }
            19 => { return self.token(TokenKind::Slash) },
            20 => {
                yyaccept = 0;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x2E => {
                        self.cursor += 1;
                        yystate = 62;
                        continue 'yyl;
                    }
                    0x30 ..= 0x39 |
                    0x5F => {
                        self.cursor += 1;
                        yystate = 20;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 21;
                        continue 'yyl;
                    }
                }
            }
            21 => { return self.int() },
            22 => { return self.token(TokenKind::Colon) },
            23 => { return self.token(TokenKind::Semicolon) },
            24 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x3D => {
                        self.cursor += 1;
                        yystate = 64;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 25;
                        continue 'yyl;
                    }
                }
            }
            25 => { return self.token(TokenKind::Lt) },
            26 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x3D => {
                        self.cursor += 1;
                        yystate = 65;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 27;
                        continue 'yyl;
                    }
                }
            }
            27 => { return self.token(TokenKind::Eq) },
            28 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x3D => {
                        self.cursor += 1;
                        yystate = 66;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 29;
                        continue 'yyl;
                    }
                }
            }
            29 => { return self.token(TokenKind::Gt) },
            30 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                yystate = 31;
                continue 'yyl;
            }
            31 => {
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 32;
                        continue 'yyl;
                    }
                }
            }
            32 => { return self.ident() },
            33 => { return self.token(TokenKind::LBracket) },
            34 => { return self.token(TokenKind::RBracket) },
            35 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 36;
                        continue 'yyl;
                    }
                }
            }
            36 => { return self.token(TokenKind::Underscore) },
            37 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 67;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            38 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 68;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            39 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 69;
                        continue 'yyl;
                    }
                    0x6F => {
                        self.cursor += 1;
                        yystate = 70;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            40 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 71;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            41 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 72;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 73;
                        continue 'yyl;
                    }
                    0x6F => {
                        self.cursor += 1;
                        yystate = 75;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            42 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x66 => {
                        self.cursor += 1;
                        yystate = 76;
                        continue 'yyl;
                    }
                    0x6D => {
                        self.cursor += 1;
                        yystate = 78;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 79;
                        continue 'yyl;
                    }
                    0x73 => {
                        self.cursor += 1;
                        yystate = 81;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            43 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 83;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            44 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 84;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            45 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6F => {
                        self.cursor += 1;
                        yystate = 85;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            46 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 86;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 88;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            47 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 90;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 91;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            48 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 92;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            49 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 93;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 94;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            50 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x68 => {
                        self.cursor += 1;
                        yystate = 95;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 96;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            51 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x73 => {
                        self.cursor += 1;
                        yystate = 97;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            52 => { return self.token(TokenKind::LBrace) },
            53 => { if self.interpolation_depth > 0 { self.cond = YYC_STRING; self.interpolation_depth -= 1; }; return self.token(TokenKind::RBrace) },
            54 => { return self.token(TokenKind::Neq) },
            55 => { return self.token(TokenKind::StarStar) },
            56 => { return self.token(TokenKind::StarEq) },
            57 => { return self.token(TokenKind::PlusEq) },
            58 => { return self.token(TokenKind::MinusEq) },
            59 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x01 ..= 0x09 |
                    0x0B ..= 0x7F => {
                        self.cursor += 1;
                        yystate = 59;
                        continue 'yyl;
                    }
                    0xC2 ..= 0xDF => {
                        self.cursor += 1;
                        yystate = 98;
                        continue 'yyl;
                    }
                    0xE0 => {
                        self.cursor += 1;
                        yystate = 99;
                        continue 'yyl;
                    }
                    0xE1 ..= 0xEF => {
                        self.cursor += 1;
                        yystate = 100;
                        continue 'yyl;
                    }
                    0xF0 => {
                        self.cursor += 1;
                        yystate = 101;
                        continue 'yyl;
                    }
                    0xF1 ..= 0xF3 => {
                        self.cursor += 1;
                        yystate = 102;
                        continue 'yyl;
                    }
                    0xF4 => {
                        self.cursor += 1;
                        yystate = 103;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 60;
                        continue 'yyl;
                    }
                }
            }
            60 => { return self.token(TokenKind::Comment(self.token_text())) },
            61 => { return self.token(TokenKind::SlashEq) },
            62 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 => {
                        self.cursor += 1;
                        yystate = 104;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            63 => {
                self.cursor = self.marker;
                if yyaccept == 0 {
                    yystate = 21;
                    continue 'yyl;
                } else {
                    yystate = 60;
                    continue 'yyl;
                }
            }
            64 => { return self.token(TokenKind::LtEq) },
            65 => { return self.token(TokenKind::EqEq) },
            66 => { return self.token(TokenKind::GtEq) },
            67 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x64 => {
                        self.cursor += 1;
                        yystate = 106;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            68 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 108;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            69 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 109;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            70 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 110;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            71 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 111;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            72 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 112;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            73 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 74;
                        continue 'yyl;
                    }
                }
            }
            74 => { return self.token(TokenKind::Fn) },
            75 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 113;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            76 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 77;
                        continue 'yyl;
                    }
                }
            }
            77 => { return self.token(TokenKind::If) },
            78 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x70 => {
                        self.cursor += 1;
                        yystate = 115;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            79 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x73 |
                    0x75 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 116;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 80;
                        continue 'yyl;
                    }
                }
            }
            80 => { return self.token(TokenKind::In) },
            81 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 82;
                        continue 'yyl;
                    }
                }
            }
            82 => { return self.token(TokenKind::Is) },
            83 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 117;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            84 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 119;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            85 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 121;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            86 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 87;
                        continue 'yyl;
                    }
                }
            }
            87 => { return self.token(TokenKind::On) },
            88 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 89;
                        continue 'yyl;
                    }
                }
            }
            89 => { return self.token(TokenKind::Or) },
            90 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x69 => {
                        self.cursor += 1;
                        yystate = 122;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            91 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x62 => {
                        self.cursor += 1;
                        yystate = 123;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            92 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 124;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            93 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 125;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            94 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 126;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            95 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 127;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            96 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 128;
                        continue 'yyl;
                    }
                    0x79 => {
                        self.cursor += 1;
                        yystate = 129;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            97 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 131;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            98 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 59;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            99 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0xA0 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 98;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            100 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 98;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            101 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x90 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 100;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            102 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 100;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            103 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0x8F => {
                        self.cursor += 1;
                        yystate = 100;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 63;
                        continue 'yyl;
                    }
                }
            }
            104 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 => {
                        self.cursor += 1;
                        yystate = 104;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 105;
                        continue 'yyl;
                    }
                }
            }
            105 => { return self.float() },
            106 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 107;
                        continue 'yyl;
                    }
                }
            }
            107 => { return self.token(TokenKind::And) },
            108 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 133;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            109 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x63 => {
                        self.cursor += 1;
                        yystate = 134;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            110 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 135;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            111 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6D => {
                        self.cursor += 1;
                        yystate = 136;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            112 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x73 => {
                        self.cursor += 1;
                        yystate = 138;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            113 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 114;
                        continue 'yyl;
                    }
                }
            }
            114 => { return self.token(TokenKind::For) },
            115 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 139;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            116 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 141;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            117 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 118;
                        continue 'yyl;
                    }
                }
            }
            118 => { return self.token(TokenKind::Let) },
            119 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 120;
                        continue 'yyl;
                    }
                }
            }
            120 => { return self.token(TokenKind::Mut) },
            121 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 142;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            122 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x76 => {
                        self.cursor += 1;
                        yystate = 144;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            123 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 145;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            124 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 146;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            125 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x66 => {
                        self.cursor += 1;
                        yystate = 147;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            126 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 149;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            127 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6F => {
                        self.cursor += 1;
                        yystate = 150;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            128 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 151;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            129 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 130;
                        continue 'yyl;
                    }
                }
            }
            130 => { return self.token(TokenKind::Try) },
            131 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 132;
                        continue 'yyl;
                    }
                }
            }
            132 => { return self.token(TokenKind::Use) },
            133 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6B => {
                        self.cursor += 1;
                        yystate = 153;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            134 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x68 => {
                        self.cursor += 1;
                        yystate = 155;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            135 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x69 => {
                        self.cursor += 1;
                        yystate = 157;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            136 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 137;
                        continue 'yyl;
                    }
                }
            }
            137 => { return self.token(TokenKind::Enum) },
            138 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 158;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            139 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 140;
                        continue 'yyl;
                    }
                }
            }
            140 => { return self.token(TokenKind::Impl) },
            141 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 160;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            142 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 143;
                        continue 'yyl;
                    }
                }
            }
            143 => { return self.token(TokenKind::None) },
            144 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 161;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            145 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x69 => {
                        self.cursor += 1;
                        yystate = 162;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            146 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x72 => {
                        self.cursor += 1;
                        yystate = 163;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            147 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 148;
                        continue 'yyl;
                    }
                }
            }
            148 => { return self.token(TokenKind::Self_) },
            149 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x63 => {
                        self.cursor += 1;
                        yystate = 164;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            150 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x77 => {
                        self.cursor += 1;
                        yystate = 165;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            151 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 152;
                        continue 'yyl;
                    }
                }
            }
            152 => { return self.token(TokenKind::BoolLiteral(true)) },
            153 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 154;
                        continue 'yyl;
                    }
                }
            }
            154 => { return self.token(TokenKind::Break) },
            155 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 156;
                        continue 'yyl;
                    }
                }
            }
            156 => { return self.token(TokenKind::Catch) },
            157 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 167;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            158 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 159;
                        continue 'yyl;
                    }
                }
            }
            159 => { return self.token(TokenKind::BoolLiteral(false)) },
            160 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 168;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            161 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 169;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            162 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x63 => {
                        self.cursor += 1;
                        yystate = 170;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            163 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6E => {
                        self.cursor += 1;
                        yystate = 172;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            164 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x74 => {
                        self.cursor += 1;
                        yystate = 174;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            165 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 166;
                        continue 'yyl;
                    }
                }
            }
            166 => { return self.token(TokenKind::Throw) },
            167 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x75 => {
                        self.cursor += 1;
                        yystate = 176;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            168 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x61 => {
                        self.cursor += 1;
                        yystate = 177;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            169 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 178;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            170 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 171;
                        continue 'yyl;
                    }
                }
            }
            171 => { return self.token(TokenKind::Public) },
            172 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 173;
                        continue 'yyl;
                    }
                }
            }
            173 => { return self.token(TokenKind::Return) },
            174 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 175;
                        continue 'yyl;
                    }
                }
            }
            175 => { return self.token(TokenKind::Struct) },
            176 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x65 => {
                        self.cursor += 1;
                        yystate = 180;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            177 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 => {
                        yystate = 32;
                        continue 'yyl;
                    }
                    0x6C => {
                        self.cursor += 1;
                        yystate = 182;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 31;
                        continue 'yyl;
                    }
                }
            }
            178 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 179;
                        continue 'yyl;
                    }
                }
            }
            179 => { return self.token(TokenKind::Private) },
            180 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 181;
                        continue 'yyl;
                    }
                }
            }
            181 => { return self.token(TokenKind::Continue) },
            182 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x30 ..= 0x39 |
                    0x41 ..= 0x5A |
                    0x5F |
                    0x61 ..= 0x7A => {
                        self.cursor += 1;
                        yystate = 30;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 183;
                        continue 'yyl;
                    }
                }
            }
            183 => { return self.token(TokenKind::Internal) },
            184 => { self.eof = true; return self.token(TokenKind::Eof) },
            185 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 |
                    0x01 ..= 0x21 |
                    0x23 ..= 0x5B |
                    0x5D ..= 0x7A |
                    0x7C |
                    0x7E ..= 0x7F => {
                        if self.input.len() - self.cursor < 1 {
                            yystate = 214;
                            continue 'yyl;
                        }
                        self.cursor += 1;
                        yystate = 186;
                        continue 'yyl;
                    }
                    0x22 => {
                        self.cursor += 1;
                        yystate = 188;
                        continue 'yyl;
                    }
                    0x5C => {
                        self.cursor += 1;
                        yystate = 189;
                        continue 'yyl;
                    }
                    0x7B => {
                        self.cursor += 1;
                        yystate = 191;
                        continue 'yyl;
                    }
                    0x7D => {
                        self.cursor += 1;
                        yystate = 192;
                        continue 'yyl;
                    }
                    0xC2 ..= 0xDF => {
                        self.cursor += 1;
                        yystate = 194;
                        continue 'yyl;
                    }
                    0xE0 => {
                        self.cursor += 1;
                        yystate = 195;
                        continue 'yyl;
                    }
                    0xE1 ..= 0xEF => {
                        self.cursor += 1;
                        yystate = 196;
                        continue 'yyl;
                    }
                    0xF0 => {
                        self.cursor += 1;
                        yystate = 197;
                        continue 'yyl;
                    }
                    0xF1 ..= 0xF3 => {
                        self.cursor += 1;
                        yystate = 198;
                        continue 'yyl;
                    }
                    0xF4 => {
                        self.cursor += 1;
                        yystate = 199;
                        continue 'yyl;
                    }
                    _ => {
                        self.cursor += 1;
                        yystate = 193;
                        continue 'yyl;
                    }
                }
            }
            186 => {
                yyaccept = 0;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 |
                    0x01 ..= 0x21 |
                    0x23 ..= 0x5B |
                    0x5D ..= 0x7A |
                    0x7C |
                    0x7E ..= 0x7F => {
                        if self.input.len() - self.cursor < 1 {
                            yystate = 187;
                            continue 'yyl;
                        }
                        self.cursor += 1;
                        yystate = 186;
                        continue 'yyl;
                    }
                    0xC2 ..= 0xDF => {
                        self.cursor += 1;
                        yystate = 200;
                        continue 'yyl;
                    }
                    0xE0 => {
                        self.cursor += 1;
                        yystate = 202;
                        continue 'yyl;
                    }
                    0xE1 ..= 0xEF => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    0xF0 => {
                        self.cursor += 1;
                        yystate = 204;
                        continue 'yyl;
                    }
                    0xF1 ..= 0xF3 => {
                        self.cursor += 1;
                        yystate = 205;
                        continue 'yyl;
                    }
                    0xF4 => {
                        self.cursor += 1;
                        yystate = 206;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 187;
                        continue 'yyl;
                    }
                }
            }
            187 => { return self.token(TokenKind::StringLiteral(self.token_text())) },
            188 => {
                self.cond = YYC_INIT;
                { return self.token(TokenKind::StringInterpolationEnd) }
            }
            189 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x00 |
                    0x01 ..= 0x09 |
                    0x0B ..= 0x7F => {
                        if self.input.len() - self.cursor < 1 {
                            yystate = 190;
                            continue 'yyl;
                        }
                        self.cursor += 1;
                        yystate = 207;
                        continue 'yyl;
                    }
                    0xC2 ..= 0xDF => {
                        self.cursor += 1;
                        yystate = 208;
                        continue 'yyl;
                    }
                    0xE0 => {
                        self.cursor += 1;
                        yystate = 209;
                        continue 'yyl;
                    }
                    0xE1 ..= 0xEF => {
                        self.cursor += 1;
                        yystate = 210;
                        continue 'yyl;
                    }
                    0xF0 => {
                        self.cursor += 1;
                        yystate = 211;
                        continue 'yyl;
                    }
                    0xF1 ..= 0xF3 => {
                        self.cursor += 1;
                        yystate = 212;
                        continue 'yyl;
                    }
                    0xF4 => {
                        self.cursor += 1;
                        yystate = 213;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            190 => { return self.error(LexerErrorKind::UnexpectedCharacter(self.token_text())) },
            191 => {
                self.cond = YYC_INIT;
                { self.interpolation_depth += 1; return self.token(TokenKind::LBrace) }
            }
            192 => { if self.interpolation_depth > 0 { self.interpolation_depth -= 1; self.cond = YYC_STRING; return self.token(TokenKind::RBrace) } else { return self.error(LexerErrorKind::UnmatchedInterpolation(self.token_text())) } },
            193 => {
                yystate = 190;
                continue 'yyl;
            }
            194 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 186;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            195 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0xA0 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 200;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            196 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 200;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            197 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x90 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            198 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            199 => {
                yyaccept = 1;
                self.marker = self.cursor;
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0x8F => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 190;
                        continue 'yyl;
                    }
                }
            }
            200 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 186;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            201 => {
                self.cursor = self.marker;
                if yyaccept == 0 {
                    yystate = 187;
                    continue 'yyl;
                } else {
                    yystate = 190;
                    continue 'yyl;
                }
            }
            202 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0xA0 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 200;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            203 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 200;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            204 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x90 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            205 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            206 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0x8F => {
                        self.cursor += 1;
                        yystate = 203;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            207 => { return self.token(TokenKind::StringLiteral(self.token_text())); },
            208 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 207;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            209 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0xA0 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 208;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            210 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 208;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            211 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x90 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 210;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            212 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0xBF => {
                        self.cursor += 1;
                        yystate = 210;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            213 => {
                yych = *self.input.as_bytes().get(self.cursor).unwrap_or(&0);
                match yych {
                    0x80 ..= 0x8F => {
                        self.cursor += 1;
                        yystate = 210;
                        continue 'yyl;
                    }
                    _ => {
                        yystate = 201;
                        continue 'yyl;
                    }
                }
            }
            214 => { self.eof = true; return self.token(TokenKind::Eof) },
            _ => panic!("internal lexer error"),
        }
    }
}

    }
}

pub const YYC_INIT: usize = 0;
pub const YYC_STRING: usize = 185;


