[package]
name = "fowlc_parser"
repository.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fowlc_error = { workspace = true }
fowlc_lexer = { workspace = true }
fowlc_span = { workspace = true }
syntree = "0.18.0"
