[package]
name = "parser"
repository.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
error = { workspace = true }
lexer = { workspace = true }
span = { workspace = true }
syntree = "0.18.0"
