[package]
name = "fowl"
description = "A simple, explicit language"
repository.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "fowl"
path = "src/main.rs"

[dependencies]
