[package]
name = "fowl"
repository.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6", features = ["derive"] }
fowlc_common = { workspace = true }
fowlc_hir = { workspace = true }
fowlc_manifest = { workspace = true }
fowlc_package_manager = { workspace = true }
fowlc_span = { workspace = true }
semver = "1.0.28"
yansi = "1.0.1"

