name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lexer_up_to_date:
    name: Ensure lexer is generated
    # Use ubuntu 26.04 to get access to re2rust v4
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7
      - name: Download re2rust
        run: sudo apt-get install re2c -y
      - name: Print re2rust version
        run: re2rust --version
      - name: Generate the lexer
        run: re2rust libs/lexer/src/lexing.re --output libs/lexer/src/lexing.rs --no-unsafe --start-conditions --no-generation-date --no-version --verbose
      - name: Check if there are differences
        run: git diff --exit-code

