name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --workspace --verbose

  fuzz:
    name: Smoke-Test Fuzz Targets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - run: cargo install cargo-afl
    - run: cargo afl system-config

    - run: cargo afl build -p fowl-fuzz --release
    - run: timeout 60s cargo afl fuzz -i fuzz/corpus -o fuzz/artifacts -x fuzz/lang.dict target/release/fowl-fuzz

    # try zip the artifact folder to mitigate github actions not allowing ":" in file names
    - name: try zip the artifact folder
      if: failure()
      run: |
        zip -r artifacts.zip fuzz/artifacts

    # Upload fuzzing artifacts on failure for post-mortem debugging.
    - uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: fuzzing-artifacts-${{ github.sha }}
        path: artifacts.zip
